"""Ownership inventory and read-boundary DTOs for project package snapshots."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
import re
from types import MappingProxyType

from backend.domain.project_packages import PackageRecord, ProjectPackageInvalid, freeze_json_value
from backend.security.paths import UnsafeLocalPath, managed_corpus_storage_key


PROJECT_OWNED_TABLES = frozenset({
    "projects", "creative_seeds", "creative_seed_revisions", "creative_seed_heads",
    "project_seed_selection_revisions", "project_selected_seeds", "project_model_binding_revisions",
    "project_model_binding_items", "project_model_binding_heads", "market_analyses",
    "seed_inspiration_attempts", "seed_inspiration_requests", "asset_recommendation_attempts",
    "asset_recommendation_requests", "style_trial_attempts", "style_trial_requests",
    "story_engine_batches", "story_engine_options", "project_contract_drafts", "creation_contracts",
    "style_contracts", "project_contract_heads", "contract_confirmation_requests",
    "creation_contract_engine_refs", "style_contract_template_refs", "creation_contract_experience_refs",
    "creation_contract_corpus_refs", "creation_contract_corpus_fragment_refs", "project_bible_drafts",
    "bible_generation_attempts", "creation_bible_revisions", "project_bible_heads",
    "bible_confirmation_requests", "planning_drafts", "planning_generation_attempts", "planning_revisions",
    "project_planning_heads", "planning_confirmation_requests", "chapter_outline_drafts",
    "chapter_outline_generation_attempts", "chapter_outline_revisions", "project_chapter_outline_heads",
    "chapter_outline_confirmation_requests", "chapter_sessions", "working_drafts", "draft_operation_attempts",
    "draft_candidates", "working_draft_revisions", "draft_operation_events", "candidate_freeze_requests",
    "candidate_quality_reports", "finalization_change_sets", "finalization_change_set_revisions",
    "finalization_records", "final_chapters", "canon_entities", "entity_aliases", "canon_revisions",
    "canon_events", "reference_uses",
})

SHARED_EXCLUDED_TABLES = frozenset({
    "provider_profiles", "provider_profile_mutation_requests", "application_settings", "style_templates",
    "style_template_heads", "experience_cards", "experience_card_heads", "corpus_blobs", "corpus_sources",
    "corpus_source_revisions", "corpus_source_heads", "corpus_chapters", "corpus_fragments",
    "corpus_import_runs", "corpus_source_deletions", "market_sources", "market_source_policy_revisions",
    "market_source_policy_heads", "market_snapshots", "market_snapshot_entries", "market_snapshot_manifests",
    "market_source_refresh_states", "market_refresh_requests",
})

INTERNAL_NON_PACKAGE_TABLES = frozenset({
    "schema_metadata", "current_state_projections", "memory_views", "arc_projections", "plot_thread_projections",
    "projection_heads",
})

# Each project-owned table has an intentionally direct or normalized package record identity.
# Request/attempt pairs share inert history types so no command can be replayed on import.
PROJECT_TABLE_RECORD_TYPES: Mapping[str, str] = MappingProxyType({
    "projects": "project", "creative_seeds": "creative-seed", "creative_seed_revisions": "creative-seed-revision",
    "creative_seed_heads": "creative-seed-head", "project_seed_selection_revisions": "project-seed-selection-revision",
    "project_selected_seeds": "project-selected-seed", "project_model_binding_revisions": "project-model-binding-revision",
    "project_model_binding_items": "project-model-binding-item", "project_model_binding_heads": "project-model-binding-head",
    "market_analyses": "market-analysis", "seed_inspiration_attempts": "seed-inspiration-history",
    "seed_inspiration_requests": "seed-inspiration-history", "asset_recommendation_attempts": "asset-recommendation-history",
    "asset_recommendation_requests": "asset-recommendation-history", "style_trial_attempts": "style-trial-history",
    "style_trial_requests": "style-trial-history", "story_engine_batches": "story-engine-batch",
    "story_engine_options": "story-engine-option", "project_contract_drafts": "project-contract-draft",
    "creation_contracts": "creation-contract", "style_contracts": "style-contract",
    "project_contract_heads": "project-contract-head", "contract_confirmation_requests": "contract-confirmation",
    "creation_contract_engine_refs": "creation-contract-engine-ref", "style_contract_template_refs": "style-contract-template-ref",
    "creation_contract_experience_refs": "creation-contract-experience-ref", "creation_contract_corpus_refs": "creation-contract-corpus-ref",
    "creation_contract_corpus_fragment_refs": "creation-contract-corpus-fragment-ref", "project_bible_drafts": "project-bible-draft",
    "bible_generation_attempts": "bible-generation-history", "creation_bible_revisions": "creation-bible-revision",
    "project_bible_heads": "project-bible-head", "bible_confirmation_requests": "bible-confirmation",
    "planning_drafts": "planning-draft", "planning_generation_attempts": "planning-generation-history",
    "planning_revisions": "planning-revision", "project_planning_heads": "project-planning-head",
    "planning_confirmation_requests": "planning-confirmation", "chapter_outline_drafts": "chapter-outline-draft",
    "chapter_outline_generation_attempts": "chapter-outline-generation-history", "chapter_outline_revisions": "chapter-outline-revision",
    "project_chapter_outline_heads": "project-chapter-outline-head", "chapter_outline_confirmation_requests": "chapter-outline-confirmation",
    "chapter_sessions": "chapter", "working_drafts": "working-draft", "draft_operation_attempts": "operation",
    "draft_candidates": "draft-candidate", "working_draft_revisions": "working-draft-revision",
    "draft_operation_events": "operation-event", "candidate_freeze_requests": "candidate-freeze",
    "candidate_quality_reports": "candidate-quality", "finalization_change_sets": "finalization-change-set",
    "finalization_change_set_revisions": "finalization-change-set-revision", "finalization_records": "finalization-record",
    "final_chapters": "final-chapter", "canon_entities": "canon-entity", "entity_aliases": "entity-alias",
    "canon_revisions": "canon-revision", "canon_events": "canon-event", "reference_uses": "reference-use",
})

NORMALIZED_SHARED_RECORD_TYPES: Mapping[str, str] = MappingProxyType({
    "style_templates": "asset", "experience_cards": "asset", "corpus_source_revisions": "corpus-revision",
})
FROZEN_CORPUS_BLOB_TABLES = frozenset({"corpus_blobs"})
LOGICAL_REFERENCE_TARGETS: Mapping[tuple[str, str], str] = MappingProxyType({
    ("chapter_outline_drafts", "source_attempt_id"): "chapter_outline_generation_attempts",
    ("chapter_sessions", "active_draft_operation_id"): "draft_operation_attempts",
    ("planning_drafts", "source_attempt_id"): "planning_generation_attempts",
})


PROJECT_TABLE_COLUMN_POLICIES = MappingProxyType({
    table: MappingProxyType(policy)
    for table, policy in {'asset_recommendation_attempts': {'binding_hash': 'public_field',
                                       'binding_revision_id': 'logical_reference',
                                       'completed_at': 'public_field',
                                       'created_at': 'public_field',
                                       'id': 'derived',
                                       'input_manifest_hash': 'excluded_sensitive_operational',
                                       'input_manifest_json': 'excluded_sensitive_operational',
                                       'project_id': 'derived',
                                       'public_error_code': 'normalized_inert_evidence',
                                       'result_hash': 'normalized_inert_evidence',
                                       'result_json': 'public_field',
                                       'selection_revision': 'public_field',
                                       'status': 'normalized_inert_evidence'},
     'asset_recommendation_requests': {'attempt_id': 'logical_reference',
                                       'completed_at': 'public_field',
                                       'created_at': 'public_field',
                                       'id': 'derived',
                                       'idempotency_key': 'excluded_sensitive_operational',
                                       'project_id': 'derived',
                                       'public_error_code': 'normalized_inert_evidence',
                                       'request_hash': 'normalized_inert_evidence',
                                       'result_hash': 'normalized_inert_evidence',
                                       'status': 'normalized_inert_evidence'},
     'bible_confirmation_requests': {'bible_revision_id': 'logical_reference',
                                     'completed_at': 'public_field',
                                     'contract_revision': 'public_field',
                                     'created_at': 'public_field',
                                     'creation_contract_id': 'logical_reference',
                                     'creation_hash': 'public_field',
                                     'draft_hash': 'public_field',
                                     'draft_id': 'logical_reference',
                                     'draft_version': 'public_field',
                                     'id': 'derived',
                                     'idempotency_key': 'excluded_sensitive_operational',
                                     'project_id': 'derived',
                                     'public_error_code': 'normalized_inert_evidence',
                                     'request_hash': 'normalized_inert_evidence',
                                     'result_hash': 'normalized_inert_evidence',
                                     'result_revision': 'public_field',
                                     'selection_revision': 'public_field',
                                     'status': 'normalized_inert_evidence',
                                     'style_contract_id': 'logical_reference',
                                     'style_hash': 'public_field'},
     'bible_generation_attempts': {'attempt_version': 'public_field',
                                   'binding_hash': 'public_field',
                                   'binding_revision_id': 'logical_reference',
                                   'completed_at': 'public_field',
                                   'contract_revision': 'public_field',
                                   'created_at': 'public_field',
                                   'creation_contract_id': 'logical_reference',
                                   'creation_hash': 'public_field',
                                   'id': 'derived',
                                   'idempotency_key': 'excluded_sensitive_operational',
                                   'input_manifest_hash': 'excluded_sensitive_operational',
                                   'input_manifest_json': 'excluded_sensitive_operational',
                                   'lease_expires_at': 'excluded_sensitive_operational',
                                   'model_name_snapshot': 'normalized_inert_evidence',
                                   'owner_token': 'excluded_sensitive_operational',
                                   'policy_version': 'public_field',
                                   'project_id': 'derived',
                                   'provider_id': 'excluded_sensitive_operational',
                                   'public_error_code': 'normalized_inert_evidence',
                                   'request_hash': 'normalized_inert_evidence',
                                   'result_hash': 'normalized_inert_evidence',
                                   'result_json': 'public_field',
                                   'seed_hash': 'public_field',
                                   'seed_id': 'logical_reference',
                                   'seed_revision_id': 'logical_reference',
                                   'selection_revision': 'public_field',
                                   'status': 'normalized_inert_evidence',
                                   'style_contract_id': 'logical_reference',
                                   'style_hash': 'public_field'},
     'candidate_freeze_requests': {'chapter_session_id': 'logical_reference',
                                   'created_at': 'public_field',
                                   'draft_candidate_id': 'logical_reference',
                                   'id': 'derived',
                                   'idempotency_key': 'excluded_sensitive_operational',
                                   'project_id': 'derived',
                                   'request_hash': 'normalized_inert_evidence'},
     'candidate_quality_reports': {'candidate_hash': 'public_field',
                                   'chapter_session_id': 'logical_reference',
                                   'content_hash': 'public_field',
                                   'context_manifest_hash': 'public_field',
                                   'created_at': 'public_field',
                                   'deterministic_blocks_json': 'public_field',
                                   'draft_candidate_id': 'logical_reference',
                                   'expected_canon_revision': 'public_field',
                                   'expected_outline_hash': 'public_field',
                                   'expected_planning_hash': 'public_field',
                                   'findings_json': 'public_field',
                                   'id': 'derived',
                                   'model_name_snapshot': 'normalized_inert_evidence',
                                   'policy_version': 'public_field',
                                   'project_id': 'derived',
                                   'provider_id': 'excluded_sensitive_operational',
                                   'provider_profile_revision': 'public_field',
                                   'status': 'normalized_inert_evidence'},
     'canon_entities': {'canonical_name': 'public_field',
                        'created_at': 'public_field',
                        'created_revision': 'public_field',
                        'entity_type': 'public_field',
                        'id': 'derived',
                        'normalized_name': 'public_field',
                        'project_id': 'derived'},
     'canon_events': {'assertion_operator': 'public_field',
                      'confirmation_status': 'public_field',
                      'created_at': 'public_field',
                      'effective_end_chapter': 'public_field',
                      'effective_start_chapter': 'public_field',
                      'entity_id': 'logical_reference',
                      'event_order': 'public_field',
                      'evidence_json': 'public_field',
                      'fact_kind': 'public_field',
                      'field_path': 'public_field',
                      'id': 'derived',
                      'project_id': 'derived',
                      'revision_id': 'logical_reference',
                      'revision_number': 'public_field',
                      'value_cardinality': 'public_field',
                      'value_json': 'public_field'},
     'canon_revisions': {'content_hash': 'public_field',
                         'created_at': 'public_field',
                         'id': 'derived',
                         'idempotency_key': 'excluded_sensitive_operational',
                         'parent_revision_number': 'public_field',
                         'project_id': 'derived',
                         'revision_number': 'public_field',
                         'source_id': 'logical_reference',
                         'source_type': 'public_field'},
     'chapter_outline_confirmation_requests': {'canon_revision': 'public_field',
                                               'chapter_num': 'public_field',
                                               'chapter_outline_draft_id': 'logical_reference',
                                               'completed_at': 'public_field',
                                               'created_at': 'public_field',
                                               'draft_hash': 'public_field',
                                               'draft_revision': 'public_field',
                                               'expected_head_revision': 'public_field',
                                               'id': 'derived',
                                               'idempotency_key': 'excluded_sensitive_operational',
                                               'outline_revision_id': 'logical_reference',
                                               'planning_hash': 'public_field',
                                               'planning_revision': 'public_field',
                                               'planning_revision_id': 'logical_reference',
                                               'project_id': 'derived',
                                               'projection_hash': 'public_field',
                                               'projection_revision': 'public_field',
                                               'public_error_code': 'normalized_inert_evidence',
                                               'request_fingerprint': 'normalized_inert_evidence',
                                               'result_hash': 'normalized_inert_evidence',
                                               'result_revision': 'public_field',
                                               'status': 'normalized_inert_evidence'},
     'chapter_outline_drafts': {'active_slot': 'excluded_sensitive_operational',
                                'base_head_revision': 'public_field',
                                'canon_revision': 'public_field',
                                'chapter_num': 'public_field',
                                'content_hash': 'public_field',
                                'content_json': 'public_field',
                                'created_at': 'public_field',
                                'draft_revision': 'public_field',
                                'id': 'derived',
                                'planning_hash': 'public_field',
                                'planning_revision': 'public_field',
                                'planning_revision_id': 'logical_reference',
                                'project_id': 'derived',
                                'projection_hash': 'public_field',
                                'projection_revision': 'public_field',
                                'source_attempt_id': 'logical_reference',
                                'status': 'normalized_inert_evidence',
                                'updated_at': 'public_field'},
     'chapter_outline_generation_attempts': {'active_slot': 'excluded_sensitive_operational',
                                             'binding_hash': 'public_field',
                                             'binding_revision': 'public_field',
                                             'binding_revision_id': 'logical_reference',
                                             'created_at': 'public_field',
                                             'failure_code': 'public_field',
                                             'fencing_token': 'excluded_sensitive_operational',
                                             'id': 'derived',
                                             'idempotency_key': 'excluded_sensitive_operational',
                                             'input_manifest_hash': 'excluded_sensitive_operational',
                                             'input_manifest_json': 'excluded_sensitive_operational',
                                             'lease_expires_at': 'excluded_sensitive_operational',
                                             'loaded_at': 'public_field',
                                             'loaded_outline_draft_revision': 'public_field',
                                             'model_name_snapshot': 'normalized_inert_evidence',
                                             'operation_id': 'logical_reference',
                                             'outline_draft_id': 'logical_reference',
                                             'project_id': 'derived',
                                             'provider_id': 'excluded_sensitive_operational',
                                             'request_fingerprint': 'normalized_inert_evidence',
                                             'result_content_hash': 'public_field',
                                             'result_content_json': 'public_field',
                                             'status': 'normalized_inert_evidence',
                                             'updated_at': 'public_field'},
     'chapter_outline_revisions': {'canon_revision': 'public_field',
                                   'chapter_num': 'public_field',
                                   'content_hash': 'public_field',
                                   'content_json': 'public_field',
                                   'created_at': 'public_field',
                                   'id': 'derived',
                                   'parent_revision': 'public_field',
                                   'planning_hash': 'public_field',
                                   'planning_revision': 'public_field',
                                   'planning_revision_id': 'logical_reference',
                                   'project_id': 'derived',
                                   'projection_hash': 'public_field',
                                   'projection_revision': 'public_field',
                                   'revision': 'public_field'},
     'chapter_sessions': {'active_draft_operation_id': 'logical_reference',
                          'chapter_num': 'public_field',
                          'chapter_outline_hash': 'public_field',
                          'chapter_outline_revision': 'public_field',
                          'chapter_outline_revision_id': 'logical_reference',
                          'created_at': 'public_field',
                          'draft_operation_fencing_token': 'excluded_sensitive_operational',
                          'expected_canon_revision': 'public_field',
                          'finalized_at': 'public_field',
                          'id': 'derived',
                          'planning_hash': 'public_field',
                          'planning_revision': 'public_field',
                          'planning_revision_id': 'logical_reference',
                          'project_id': 'derived',
                          'status': 'normalized_inert_evidence',
                          'story_block_hash': 'public_field',
                          'story_block_id': 'logical_reference',
                          'story_block_revision': 'public_field'},
     'contract_confirmation_requests': {'completed_at': 'public_field',
                                        'created_at': 'public_field',
                                        'creation_contract_id': 'logical_reference',
                                        'id': 'derived',
                                        'idempotency_key': 'excluded_sensitive_operational',
                                        'project_id': 'derived',
                                        'public_error_code': 'normalized_inert_evidence',
                                        'request_hash': 'normalized_inert_evidence',
                                        'result_revision': 'public_field',
                                        'selection_revision': 'public_field',
                                        'status': 'normalized_inert_evidence',
                                        'style_contract_id': 'logical_reference'},
     'creation_bible_revisions': {'binding_hash': 'public_field',
                                  'binding_revision_id': 'logical_reference',
                                  'confirmed_at': 'public_field',
                                  'content_hash': 'public_field',
                                  'content_json': 'public_field',
                                  'contract_revision': 'public_field',
                                  'creation_contract_id': 'logical_reference',
                                  'creation_hash': 'public_field',
                                  'id': 'derived',
                                  'policy_version': 'public_field',
                                  'project_id': 'derived',
                                  'revision': 'public_field',
                                  'seed_hash': 'public_field',
                                  'seed_id': 'logical_reference',
                                  'seed_revision_id': 'logical_reference',
                                  'selection_revision': 'public_field',
                                  'style_contract_id': 'logical_reference',
                                  'style_hash': 'public_field'},
     'creation_contract_corpus_fragment_refs': {'chapter_char_end': 'public_field',
                                                'chapter_char_start': 'public_field',
                                                'corpus_chapter_id': 'logical_reference',
                                                'corpus_fragment_id': 'logical_reference',
                                                'corpus_source_id': 'logical_reference',
                                                'creation_contract_id': 'logical_reference',
                                                'fragment_hash': 'public_field',
                                                'reference_use': 'public_field',
                                                'sort_order': 'public_field',
                                                'source_hash': 'public_field',
                                                'source_revision': 'public_field'},
     'creation_contract_corpus_refs': {'corpus_source_id': 'logical_reference',
                                       'creation_contract_id': 'logical_reference',
                                       'selection_mode': 'public_field',
                                       'sort_order': 'public_field',
                                       'source_hash': 'public_field',
                                       'source_revision': 'public_field'},
     'creation_contract_engine_refs': {'creation_contract_id': 'logical_reference',
                                       'engine_hash': 'public_field',
                                       'engine_option_id': 'logical_reference',
                                       'project_id': 'derived'},
     'creation_contract_experience_refs': {'asset_hash': 'public_field',
                                           'asset_revision': 'public_field',
                                           'creation_contract_id': 'logical_reference',
                                           'experience_card_id': 'logical_reference',
                                           'sort_order': 'public_field'},
     'creation_contracts': {'binding_hash': 'public_field',
                            'binding_revision_id': 'logical_reference',
                            'channel_profile_key': 'public_field',
                            'chapter_capacity_policy': 'public_field',
                            'confirmed_at': 'public_field',
                            'content_hash': 'public_field',
                            'content_json': 'public_field',
                            'genre_profile_key': 'public_field',
                            'id': 'derived',
                            'project_id': 'derived',
                            'quality_charter_version': 'public_field',
                            'reference_manifest_hash': 'public_field',
                            'reference_manifest_json': 'public_field',
                            'revision': 'public_field',
                            'seed_hash': 'public_field',
                            'seed_id': 'logical_reference',
                            'seed_revision_id': 'logical_reference',
                            'selection_revision': 'public_field',
                            'total_word_max': 'public_field',
                            'total_word_min': 'public_field'},
     'creative_seed_heads': {'content_hash': 'public_field',
                             'revision': 'public_field',
                             'revision_id': 'logical_reference',
                             'seed_id': 'logical_reference',
                             'updated_at': 'public_field'},
     'creative_seed_revisions': {'content_hash': 'public_field',
                                 'created_at': 'public_field',
                                 'id': 'derived',
                                 'payload_json': 'public_field',
                                 'project_id': 'derived',
                                 'revision': 'public_field',
                                 'seed_id': 'logical_reference'},
     'creative_seeds': {'created_at': 'public_field',
                        'id': 'derived',
                        'project_id': 'derived',
                        'status': 'normalized_inert_evidence',
                        'updated_at': 'public_field'},
     'draft_candidates': {'basis_hash': 'public_field',
                          'chapter_session_id': 'logical_reference',
                          'content': 'public_field',
                          'content_hash': 'public_field',
                          'created_at': 'public_field',
                          'id': 'derived',
                          'project_id': 'derived',
                          'provenance_json': 'public_field',
                          'working_draft_revision': 'public_field'},
     'draft_operation_attempts': {'active_slot': 'excluded_sensitive_operational',
                                  'base_working_draft_hash': 'public_field',
                                  'base_working_draft_revision': 'public_field',
                                  'cancelled_at': 'public_field',
                                  'chapter_session_id': 'logical_reference',
                                  'completed_at': 'public_field',
                                  'created_at': 'public_field',
                                  'failure_code': 'public_field',
                                  'fencing_token': 'excluded_sensitive_operational',
                                  'heartbeat_at': 'public_field',
                                  'id': 'derived',
                                  'idempotency_key': 'excluded_sensitive_operational',
                                  'input_manifest_hash': 'excluded_sensitive_operational',
                                  'input_manifest_json': 'excluded_sensitive_operational',
                                  'last_event_sequence': 'public_field',
                                  'lease_expires_at': 'excluded_sensitive_operational',
                                  'model_name_snapshot': 'normalized_inert_evidence',
                                  'operation_type': 'public_field',
                                  'partial_output_hash': 'excluded_sensitive_operational',
                                  'partial_output_scalars': 'excluded_sensitive_operational',
                                  'partial_output_text': 'excluded_sensitive_operational',
                                  'project_id': 'derived',
                                  'provider_id': 'excluded_sensitive_operational',
                                  'request_fingerprint': 'normalized_inert_evidence',
                                  'result_content_hash': 'public_field',
                                  'result_working_draft_revision': 'public_field',
                                  'status': 'normalized_inert_evidence',
                                  'updated_at': 'public_field'},
     'draft_operation_events': {'closed_payload_json': 'excluded_sensitive_operational',
                                'created_at': 'public_field',
                                'draft_operation_id': 'logical_reference',
                                'event_type': 'public_field',
                                'id': 'derived',
                                'project_id': 'derived',
                                'sequence_num': 'public_field'},
     'entity_aliases': {'alias': 'public_field',
                        'created_at': 'public_field',
                        'created_revision': 'public_field',
                        'entity_id': 'logical_reference',
                        'id': 'derived',
                        'normalized_alias': 'public_field',
                        'project_id': 'derived'},
     'final_chapters': {'canon_revision': 'public_field',
                        'chapter_num': 'public_field',
                        'chapter_outline_hash': 'public_field',
                        'chapter_outline_revision': 'public_field',
                        'chapter_outline_revision_id': 'logical_reference',
                        'chapter_session_id': 'logical_reference',
                        'content': 'public_field',
                        'content_hash': 'public_field',
                        'draft_candidate_id': 'logical_reference',
                        'finalization_record_id': 'logical_reference',
                        'finalized_at': 'public_field',
                        'id': 'derived',
                        'planning_hash': 'public_field',
                        'planning_revision': 'public_field',
                        'planning_revision_id': 'logical_reference',
                        'project_id': 'derived',
                        'title': 'public_field'},
     'finalization_change_set_revisions': {'change_set_id': 'logical_reference',
                                           'content_hash': 'public_field',
                                           'created_at': 'public_field',
                                           'id': 'derived',
                                           'payload_json': 'public_field',
                                           'project_id': 'derived',
                                           'revision': 'public_field',
                                           'source': 'public_field'},
     'finalization_change_sets': {'active_slot': 'excluded_sensitive_operational',
                                  'candidate_hash': 'public_field',
                                  'chapter_session_id': 'logical_reference',
                                  'confirmed_at': 'public_field',
                                  'confirmed_revision': 'public_field',
                                  'confirmed_revision_hash': 'public_field',
                                  'context_manifest_hash': 'public_field',
                                  'context_manifest_json': 'public_field',
                                  'created_at': 'public_field',
                                  'current_revision': 'public_field',
                                  'current_revision_hash': 'public_field',
                                  'draft_candidate_id': 'logical_reference',
                                  'expected_canon_revision': 'public_field',
                                  'expected_outline_hash': 'public_field',
                                  'expected_planning_hash': 'public_field',
                                  'extraction_id': 'logical_reference',
                                  'id': 'derived',
                                  'idempotency_key': 'excluded_sensitive_operational',
                                  'project_id': 'derived',
                                  'quality_report_id': 'logical_reference',
                                  'request_fingerprint': 'normalized_inert_evidence',
                                  'status': 'normalized_inert_evidence',
                                  'updated_at': 'public_field'},
     'finalization_records': {'candidate_hash': 'public_field',
                              'change_set_hash': 'public_field',
                              'change_set_id': 'logical_reference',
                              'change_set_revision': 'public_field',
                              'chapter_session_id': 'logical_reference',
                              'committed_canon_revision': 'public_field',
                              'draft_candidate_id': 'logical_reference',
                              'expected_canon_revision': 'public_field',
                              'finalized_at': 'public_field',
                              'id': 'derived',
                              'idempotency_key': 'excluded_sensitive_operational',
                              'project_id': 'derived',
                              'request_fingerprint': 'normalized_inert_evidence',
                              'result_payload_json': 'public_field'},
     'market_analyses': {'analysis_json': 'public_field',
                         'binding_hash': 'public_field',
                         'binding_revision_id': 'logical_reference',
                         'completed_at': 'public_field',
                         'created_at': 'public_field',
                         'id': 'derived',
                         'idempotency_key': 'excluded_sensitive_operational',
                         'input_manifest_hash': 'excluded_sensitive_operational',
                         'input_manifest_json': 'excluded_sensitive_operational',
                         'policy_version': 'public_field',
                         'project_id': 'derived',
                         'public_error_code': 'normalized_inert_evidence',
                         'request_hash': 'normalized_inert_evidence',
                         'result_hash': 'normalized_inert_evidence',
                         'status': 'normalized_inert_evidence'},
     'planning_confirmation_requests': {'completed_at': 'public_field',
                                        'created_at': 'public_field',
                                        'draft_hash': 'public_field',
                                        'draft_revision': 'public_field',
                                        'expected_head_revision': 'public_field',
                                        'id': 'derived',
                                        'idempotency_key': 'excluded_sensitive_operational',
                                        'planning_draft_id': 'logical_reference',
                                        'planning_revision_id': 'logical_reference',
                                        'project_id': 'derived',
                                        'public_error_code': 'normalized_inert_evidence',
                                        'request_fingerprint': 'normalized_inert_evidence',
                                        'result_hash': 'normalized_inert_evidence',
                                        'result_revision': 'public_field',
                                        'status': 'normalized_inert_evidence'},
     'planning_drafts': {'active_slot': 'excluded_sensitive_operational',
                         'base_head_revision': 'public_field',
                         'bible_hash': 'public_field',
                         'bible_revision': 'public_field',
                         'bible_revision_id': 'logical_reference',
                         'content_hash': 'public_field',
                         'content_json': 'public_field',
                         'contract_revision': 'public_field',
                         'created_at': 'public_field',
                         'creation_contract_id': 'logical_reference',
                         'creation_hash': 'public_field',
                         'draft_revision': 'public_field',
                         'id': 'derived',
                         'project_id': 'derived',
                         'seed_hash': 'public_field',
                         'seed_id': 'logical_reference',
                         'seed_revision_id': 'logical_reference',
                         'selection_revision': 'public_field',
                         'source_attempt_id': 'logical_reference',
                         'status': 'normalized_inert_evidence',
                         'style_contract_id': 'logical_reference',
                         'style_hash': 'public_field',
                         'updated_at': 'public_field'},
     'planning_generation_attempts': {'active_slot': 'excluded_sensitive_operational',
                                      'binding_hash': 'public_field',
                                      'binding_revision': 'public_field',
                                      'binding_revision_id': 'logical_reference',
                                      'created_at': 'public_field',
                                      'draft_id': 'logical_reference',
                                      'failure_code': 'public_field',
                                      'fencing_token': 'excluded_sensitive_operational',
                                      'id': 'derived',
                                      'idempotency_key': 'excluded_sensitive_operational',
                                      'input_manifest_hash': 'excluded_sensitive_operational',
                                      'input_manifest_json': 'excluded_sensitive_operational',
                                      'lease_expires_at': 'excluded_sensitive_operational',
                                      'loaded_at': 'public_field',
                                      'loaded_draft_revision': 'public_field',
                                      'model_name_snapshot': 'normalized_inert_evidence',
                                      'operation_id': 'logical_reference',
                                      'project_id': 'derived',
                                      'provider_id': 'excluded_sensitive_operational',
                                      'request_fingerprint': 'normalized_inert_evidence',
                                      'result_content_hash': 'public_field',
                                      'result_content_json': 'public_field',
                                      'status': 'normalized_inert_evidence',
                                      'updated_at': 'public_field'},
     'planning_revisions': {'bible_hash': 'public_field',
                            'bible_revision': 'public_field',
                            'bible_revision_id': 'logical_reference',
                            'content_hash': 'public_field',
                            'content_json': 'public_field',
                            'contract_revision': 'public_field',
                            'created_at': 'public_field',
                            'creation_contract_id': 'logical_reference',
                            'creation_hash': 'public_field',
                            'id': 'derived',
                            'parent_revision': 'public_field',
                            'project_id': 'derived',
                            'revision': 'public_field',
                            'seed_hash': 'public_field',
                            'seed_id': 'logical_reference',
                            'seed_revision_id': 'logical_reference',
                            'selection_revision': 'public_field',
                            'style_contract_id': 'logical_reference',
                            'style_hash': 'public_field'},
     'project_bible_drafts': {'active_slot': 'excluded_sensitive_operational',
                              'base_head_revision': 'public_field',
                              'binding_hash': 'public_field',
                              'binding_revision_id': 'logical_reference',
                              'content_hash': 'public_field',
                              'contract_revision': 'public_field',
                              'created_at': 'public_field',
                              'creation_contract_id': 'logical_reference',
                              'creation_hash': 'public_field',
                              'draft_json': 'public_field',
                              'draft_version': 'public_field',
                              'id': 'derived',
                              'policy_version': 'public_field',
                              'project_id': 'derived',
                              'seed_hash': 'public_field',
                              'seed_id': 'logical_reference',
                              'seed_revision_id': 'logical_reference',
                              'selection_revision': 'public_field',
                              'style_contract_id': 'logical_reference',
                              'style_hash': 'public_field',
                              'updated_at': 'public_field'},
     'project_bible_heads': {'bible_revision_id': 'logical_reference',
                             'content_hash': 'public_field',
                             'project_id': 'derived',
                             'revision': 'public_field',
                             'updated_at': 'public_field'},
     'project_chapter_outline_heads': {'chapter_num': 'public_field',
                                       'content_hash': 'public_field',
                                       'outline_revision_id': 'logical_reference',
                                       'project_id': 'derived',
                                       'revision': 'public_field',
                                       'updated_at': 'public_field'},
     'project_contract_drafts': {'base_head_revision': 'public_field',
                                 'content_hash': 'public_field',
                                 'created_at': 'public_field',
                                 'draft_json': 'public_field',
                                 'draft_version': 'public_field',
                                 'engine_option_id': 'logical_reference',
                                 'id': 'derived',
                                 'project_id': 'derived',
                                 'seed_hash': 'public_field',
                                 'seed_revision_id': 'logical_reference',
                                 'selection_revision': 'public_field',
                                 'updated_at': 'public_field'},
     'project_contract_heads': {'creation_contract_id': 'logical_reference',
                                'creation_hash': 'public_field',
                                'project_id': 'derived',
                                'revision': 'public_field',
                                'style_contract_id': 'logical_reference',
                                'style_hash': 'public_field',
                                'updated_at': 'public_field'},
     'project_model_binding_heads': {'binding_revision_id': 'logical_reference',
                                     'content_hash': 'public_field',
                                     'project_id': 'derived',
                                     'revision': 'public_field',
                                     'updated_at': 'public_field'},
     'project_model_binding_items': {'binding_revision_id': 'logical_reference',
                                     'item_hash': 'public_field',
                                     'model_name_snapshot': 'normalized_inert_evidence',
                                     'provider_id': 'excluded_sensitive_operational',
                                     'provider_name_snapshot': 'public_field',
                                     'resolution_status': 'public_field',
                                     'task_key': 'public_field'},
     'project_model_binding_revisions': {'content_hash': 'public_field',
                                         'created_at': 'public_field',
                                         'id': 'derived',
                                         'project_id': 'derived',
                                         'revision': 'public_field',
                                         'source_project_id': 'logical_reference'},
     'project_planning_heads': {'content_hash': 'public_field',
                                'planning_revision_id': 'logical_reference',
                                'project_id': 'derived',
                                'revision': 'public_field',
                                'updated_at': 'public_field'},
     'project_seed_selection_revisions': {'project_id': 'derived',
                                          'seed_hash': 'public_field',
                                          'seed_id': 'logical_reference',
                                          'seed_revision_id': 'logical_reference',
                                          'selected_at': 'public_field',
                                          'selection_revision': 'public_field'},
     'project_selected_seeds': {'project_id': 'derived',
                                'seed_hash': 'public_field',
                                'seed_id': 'logical_reference',
                                'seed_revision_id': 'logical_reference',
                                'selected_at': 'public_field',
                                'selection_revision': 'public_field',
                                'updated_at': 'public_field'},
     'projects': {'archived_at': 'public_field',
                  'created_at': 'public_field',
                  'current_chapter': 'public_field',
                  'description': 'public_field',
                  'genre': 'public_field',
                  'id': 'derived',
                  'lifecycle_revision': 'public_field',
                  'status': 'normalized_inert_evidence',
                  'target_chapters': 'public_field',
                  'target_words': 'public_field',
                  'title': 'public_field',
                  'updated_at': 'public_field'},
     'reference_uses': {'chapter_session_id': 'logical_reference',
                        'corpus_chapter_id': 'logical_reference',
                        'corpus_source_id': 'logical_reference',
                        'created_at': 'public_field',
                        'draft_candidate_id': 'logical_reference',
                        'id': 'derived',
                        'location_end': 'public_field',
                        'location_start': 'public_field',
                        'project_id': 'derived',
                        'reference_purpose': 'public_field',
                        'referenced_text_hash': 'public_field'},
     'seed_inspiration_attempts': {'binding_hash': 'public_field',
                                   'binding_revision_id': 'logical_reference',
                                   'completed_at': 'public_field',
                                   'created_at': 'public_field',
                                   'id': 'derived',
                                   'input_manifest_hash': 'excluded_sensitive_operational',
                                   'input_manifest_json': 'excluded_sensitive_operational',
                                   'market_analysis_hash': 'public_field',
                                   'market_analysis_id': 'logical_reference',
                                   'market_snapshot_hash': 'public_field',
                                   'market_snapshot_id': 'logical_reference',
                                   'market_source_id': 'logical_reference',
                                   'project_id': 'derived',
                                   'public_error_code': 'normalized_inert_evidence',
                                   'result_hash': 'normalized_inert_evidence',
                                   'result_json': 'public_field',
                                   'selection_revision': 'public_field',
                                   'status': 'normalized_inert_evidence'},
     'seed_inspiration_requests': {'attempt_id': 'logical_reference',
                                   'completed_at': 'public_field',
                                   'created_at': 'public_field',
                                   'id': 'derived',
                                   'idempotency_key': 'excluded_sensitive_operational',
                                   'project_id': 'derived',
                                   'public_error_code': 'normalized_inert_evidence',
                                   'request_hash': 'normalized_inert_evidence',
                                   'result_hash': 'normalized_inert_evidence',
                                   'status': 'normalized_inert_evidence'},
     'story_engine_batches': {'attempt_id': 'logical_reference',
                              'attempt_started_at': 'public_field',
                              'binding_hash': 'public_field',
                              'binding_revision_id': 'logical_reference',
                              'created_at': 'public_field',
                              'finished_at': 'public_field',
                              'id': 'derived',
                              'idempotency_key': 'excluded_sensitive_operational',
                              'lease_expires_at': 'excluded_sensitive_operational',
                              'model_name_snapshot': 'normalized_inert_evidence',
                              'project_id': 'derived',
                              'provider_id': 'excluded_sensitive_operational',
                              'public_error_code': 'normalized_inert_evidence',
                              'raw_response_hash': 'excluded_sensitive_operational',
                              'raw_response_text': 'excluded_sensitive_operational',
                              'request_hash': 'normalized_inert_evidence',
                              'request_json': 'excluded_sensitive_operational',
                              'seed_hash': 'public_field',
                              'seed_id': 'logical_reference',
                              'seed_revision_id': 'logical_reference',
                              'selection_revision': 'public_field',
                              'source_type': 'public_field',
                              'status': 'normalized_inert_evidence'},
     'story_engine_options': {'batch_id': 'logical_reference',
                              'content_hash': 'public_field',
                              'created_at': 'public_field',
                              'id': 'derived',
                              'option_order': 'public_field',
                              'payload_json': 'public_field',
                              'project_id': 'derived',
                              'selection_revision': 'public_field'},
     'style_contract_template_refs': {'asset_hash': 'public_field',
                                      'asset_revision': 'public_field',
                                      'role': 'public_field',
                                      'sort_order': 'public_field',
                                      'style_contract_id': 'logical_reference',
                                      'style_template_id': 'logical_reference'},
     'style_contracts': {'confirmed_at': 'public_field',
                         'content_hash': 'public_field',
                         'creation_contract_id': 'logical_reference',
                         'dislikes_json': 'public_field',
                         'id': 'derived',
                         'likes_json': 'public_field',
                         'merged_style_json': 'public_field',
                         'project_id': 'derived',
                         'revision': 'public_field'},
     'style_trial_attempts': {'binding_hash': 'public_field',
                              'binding_revision_id': 'logical_reference',
                              'completed_at': 'public_field',
                              'created_at': 'public_field',
                              'id': 'derived',
                              'input_manifest_hash': 'excluded_sensitive_operational',
                              'input_manifest_json': 'excluded_sensitive_operational',
                              'project_id': 'derived',
                              'public_error_code': 'normalized_inert_evidence',
                              'result_hash': 'normalized_inert_evidence',
                              'result_json': 'public_field',
                              'selection_revision': 'public_field',
                              'status': 'normalized_inert_evidence'},
     'style_trial_requests': {'attempt_id': 'logical_reference',
                              'completed_at': 'public_field',
                              'created_at': 'public_field',
                              'id': 'derived',
                              'idempotency_key': 'excluded_sensitive_operational',
                              'project_id': 'derived',
                              'public_error_code': 'normalized_inert_evidence',
                              'request_hash': 'normalized_inert_evidence',
                              'result_hash': 'normalized_inert_evidence',
                              'status': 'normalized_inert_evidence'},
     'working_draft_revisions': {'chapter_session_id': 'logical_reference',
                                 'content': 'public_field',
                                 'content_hash': 'public_field',
                                 'created_at': 'public_field',
                                 'id': 'derived',
                                 'project_id': 'derived',
                                 'replacement_reason': 'public_field',
                                 'snapshot_role': 'public_field',
                                 'source_candidate_id': 'logical_reference',
                                 'source_operation_id': 'logical_reference',
                                 'working_draft_id': 'logical_reference',
                                 'working_draft_revision': 'public_field'},
     'working_drafts': {'chapter_session_id': 'logical_reference',
                        'content': 'public_field',
                        'content_hash': 'public_field',
                        'id': 'derived',
                        'project_id': 'derived',
                        'revision': 'public_field',
                        'source_payload_json': 'public_field',
                        'updated_at': 'public_field'}}.items()
})

_NON_PACKAGE_REFERENCE_COLUMNS = frozenset({
    ("seed_inspiration_attempts", "market_source_id"), ("seed_inspiration_attempts", "market_snapshot_id"),
    ("creation_contract_corpus_refs", "corpus_source_id"),
    ("creation_contract_corpus_fragment_refs", "corpus_source_id"),
    ("creation_contract_corpus_fragment_refs", "corpus_chapter_id"),
    ("creation_contract_corpus_fragment_refs", "corpus_fragment_id"),
    ("reference_uses", "corpus_source_id"), ("reference_uses", "corpus_chapter_id"),
})
_policy_copy = {table: dict(policy) for table, policy in PROJECT_TABLE_COLUMN_POLICIES.items()}
for _table, _column in _NON_PACKAGE_REFERENCE_COLUMNS:
    _policy_copy[_table][_column] = "normalized_inert_evidence"
_policy_copy["finalization_change_sets"]["extraction_id"] = "excluded_sensitive_operational"
PROJECT_TABLE_COLUMN_POLICIES = MappingProxyType({
    table: MappingProxyType(policy) for table, policy in _policy_copy.items()
})

_policy_copy = {table: dict(policy) for table, policy in PROJECT_TABLE_COLUMN_POLICIES.items()}
for _table, _column in {
    ("planning_generation_attempts", "operation_id"),
    ("chapter_outline_generation_attempts", "operation_id"),
    ("story_engine_batches", "attempt_id"),
}:
    _policy_copy[_table][_column] = "excluded_sensitive_operational"
_policy_copy["chapter_sessions"]["story_block_id"] = "nested_logical_reference"
_policy_copy["canon_revisions"]["source_id"] = "polymorphic_logical_reference"
PROJECT_TABLE_COLUMN_POLICIES = MappingProxyType({
    table: MappingProxyType(policy) for table, policy in _policy_copy.items()
})
NESTED_LOGICAL_REFERENCE_TARGETS: Mapping[tuple[str, str], str] = MappingProxyType({
    ("chapter_sessions", "story_block_id"): "story-block",
})
POLYMORPHIC_LOGICAL_REFERENCE_TARGETS: Mapping[tuple[str, str], Mapping[str, str | None]] = MappingProxyType({
    ("canon_revisions", "source_id"): MappingProxyType({
        "bootstrap": None, "finalization": "finalization_records", "manual_test": None,
    }),
})


def _invalid() -> ProjectPackageInvalid:
    return ProjectPackageInvalid("invalid package value")


@dataclass(frozen=True, slots=True)
class FrozenCorpusBlob:
    logical_id: str
    content_hash: str
    byte_length: int
    storage_key: str = field(repr=False)

    def __post_init__(self) -> None:
        if (
            not isinstance(self.logical_id, str)
            or not re.fullmatch(r"corpus-blob:[1-9][0-9]*", self.logical_id)
            or not isinstance(self.content_hash, str)
            or not re.fullmatch(r"[0-9a-f]{64}", self.content_hash)
            or type(self.byte_length) is not int
            or self.byte_length < 0
            or not isinstance(self.storage_key, str)
        ):
            raise _invalid()
        try:
            expected_storage_key = managed_corpus_storage_key(self.content_hash)
        except UnsafeLocalPath:
            raise _invalid() from None
        if self.storage_key != expected_storage_key:
            raise _invalid()


@dataclass(frozen=True, slots=True)
class ProjectPackageSnapshot:
    source_project_logical_id: str
    lifecycle_revision: int
    graph_records: tuple[PackageRecord, ...]
    operation_records: tuple[PackageRecord, ...]
    provider_history_records: tuple[PackageRecord, ...]
    frozen_asset_records: tuple[PackageRecord, ...]
    corpus_revision_records: tuple[PackageRecord, ...]
    corpus_blobs: tuple[FrozenCorpusBlob, ...]
    projection_validation: Mapping[str, object]
    referenced_secret_values: tuple[bytes, ...] = field(repr=False)
    counts: Mapping[str, int] = field(default_factory=dict)

    def __post_init__(self) -> None:
        record_groups = (
            self.graph_records,
            self.operation_records,
            self.provider_history_records,
            self.frozen_asset_records,
            self.corpus_revision_records,
        )
        if (
            not isinstance(self.source_project_logical_id, str)
            or not re.fullmatch(r"project:[1-9][0-9]*", self.source_project_logical_id)
            or type(self.lifecycle_revision) is not int
            or self.lifecycle_revision < 0
            or any(type(group) is not tuple for group in record_groups)
            or type(self.corpus_blobs) is not tuple
            or type(self.referenced_secret_values) is not tuple
            or any(type(record) is not PackageRecord for group in record_groups for record in group)
            or any(type(blob) is not FrozenCorpusBlob for blob in self.corpus_blobs)
            or not isinstance(self.projection_validation, Mapping)
            or any(type(value) is not bytes for value in self.referenced_secret_values)
            or not isinstance(self.counts, Mapping)
            or any(not isinstance(key, str) or type(value) is not int or value < 0 for key, value in self.counts.items())
        ):
            raise _invalid()
        object.__setattr__(self, "projection_validation", freeze_json_value(self.projection_validation))
        object.__setattr__(self, "counts", MappingProxyType(dict(self.counts)))


class ProjectPackageRepository:
    """Read-only repository boundary; snapshot query implementation follows in Task 2B."""

    async def read_snapshot(self, project_id: str, expected_lifecycle_revision: int) -> ProjectPackageSnapshot:
        raise NotImplementedError
