import test from 'node:test'
import assert from 'node:assert/strict'
import { enterTopicSubject, clearTopicContext } from '../../src/application/topics/topicContext.js'
import { createDirectionCandidateController } from '../../src/application/topics/directionCandidate.js'
const subject = {kind:'direction',id:'direction-b',version:2,contentHash:'hash-b',title:'B',discussionId:'discussion-b',evidence:[{snapshotId:'snapshot-b',contentHash:'evidence-b'}]}
function fixture(){const calls=[]; const topics={sending:false,activeDiscussion:{discussion:{id:'discussion-a'}},selectedEvidence:[{snapshotId:'a'}],discussionSubject:{id:'a'},discussionRecommendation:{title:'a'},openDiscussion:async id=>{calls.push(['open',id]); topics.activeDiscussion={discussion:{id}};return topics.activeDiscussion},sendMessage:async(id,data)=>{calls.push(['send',id,data]);return {requestId:'request-b',assistantMessageId:'assistant-b',result:{candidateSuggestions:[{title:'candidate-b'}]}}},saveCandidate:async(id,data)=>{calls.push(['save',id,data]);return {candidateId:'candidate-b',version:1}}};return {topics,calls}}
test('continue uses the selected version source and replaces all old evidence',async()=>{const {topics,calls}=fixture();await enterTopicSubject(topics,subject);assert.equal(topics.activeDiscussion.discussion.id,'discussion-b');assert.deepEqual(topics.selectedEvidence,subject.evidence);assert.equal(topics.discussionSubject.id,'direction-b');assert.equal(topics.discussionRecommendation,null);assert.deepEqual(calls,[['open','discussion-b']]);clearTopicContext(topics);assert.deepEqual(topics.selectedEvidence,[]);assert.equal(topics.discussionSubject,null)})
test('failed source read leaves current context intact and does not send',async()=>{const {topics,calls}=fixture();topics.openDiscussion=async()=>{throw Error('offline')};await assert.rejects(enterTopicSubject(topics,subject));assert.equal(topics.discussionSubject.id,'a');assert.deepEqual(calls,[])})
test('candidate save retry across component remount never generates twice',async()=>{const {topics,calls}=fixture();let fail=true;const save=topics.saveCandidate;topics.saveCandidate=async(...args)=>{const result=await save(...args);if(fail)throw Error('transport');return result};const flow=createDirectionCandidateController(topics);assert.equal(await flow.generate(subject),null);assert.ok(flow.state.pending);fail=false;const remount=createDirectionCandidateController(topics);assert.equal((await remount.generate(subject)).candidateId,'candidate-b');assert.equal(calls.filter(c=>c[0]==='send').length,1);const saves=calls.filter(c=>c[0]==='save');assert.equal(saves[0][2].idempotencyKey,saves[1][2].idempotencyKey);assert.deepEqual(saves[1][2].evidence,subject.evidence)})
test('ambiguous model result cannot trigger repeat generation',async()=>{const {topics,calls}=fixture();topics.sendMessage=async()=>{calls.push('send');throw Error('timeout')};const flow=createDirectionCandidateController(topics);await flow.generate(subject);await flow.generate(subject);assert.equal(flow.state.uncertain,true);assert.equal(calls.filter(c=>c==='send').length,1)})

test('generated candidate uses the same save identity as the discussion suggestion button',async()=>{const {topicSuggestionKey}=await import('../../src/application/topics/topicSuggestionKey.js');const {topics,calls}=fixture();await createDirectionCandidateController(topics).generate(subject);assert.equal(calls.find(c=>c[0]==='save')[2].idempotencyKey,await topicSuggestionKey('discussion-b','request-b','candidate',0));assert.ok(topics.savedSuggestionKeys.includes('request-b:candidate:0'))})
